name: comment-tag-issue
description: A tool to create issues based on comment tags
author: Brandon Ryan
runs:
  using: composite
  steps:
    - uses: ./action-tag.yaml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add issue numbers to tagged comments