name: bootstrap
on:
  push:
    branches:
      - main
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Self
        uses: ./