name: bootstrap
on:
  pull_request:
    branches: [ main ]
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: make sure dist is there
        run: pwd && ls -a
      - name: Self
        uses: ./