name: bootstrap
on:
  push:
    branches:
      - main
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: List log
        run: git log -n4
      - name: Self
        uses: ./